[repos]
num_repos = 3
languages = ['typescript','javascript','python']
query = "language server"
delete_repos = true

[repo.search]
inodes_search = ['*.ts','*.js']


[package_managers]
pypi = true
npm = false

