[repos]
num_repos = 3
languages = ['javascript','typescript']
query = "esprima"
delete_repos = false

[repo.search]
inodes = ['next.config.js','tailwind.config.cjs']


[package_managers]
pypi = true
npm = false